# Generated by Django 3.2 on 2022-09-22 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('privatechat', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
